In [1]:
import pandas as pd
import time
from datetime import datetime
import csv

In [2]:
# ---------------------------------------------------------
# 1. READ SOURCE CSV
# ---------------------------------------------------------

df = pd.read_csv("GlobalWeatherRepository.csv")

print("CSV file loaded successfully!")
print("Total source records:", len(df))

CSV file loaded successfully!
Total source records: 164499

In [3]:
# ---------------------------------------------------------
# 2. CHECK REQUIRED COLUMNS
# ---------------------------------------------------------

required_columns = [
    "location_name",
    "latitude",
    "longitude",
    "temperature_celsius",
    "humidity"
]

for column in required_columns:
    if column not in df.columns:
        raise ValueError("Column not found: " + column)

print("Required columns found!")

Required columns found!

In [4]:
# ---------------------------------------------------------
# 3. REMOVE EMPTY RECORDS
# ---------------------------------------------------------

df = df.dropna(subset=required_columns).reset_index(drop=True)

print("Valid source records:", len(df))

Valid source records: 164499

In [5]:
# ---------------------------------------------------------
# 4. CREATE CONTAINER IDs
# ---------------------------------------------------------

container_ids = {}

for number, location in enumerate(
    df["location_name"].unique(),
    start=1
):
    container_ids[location] = "CONT_{:04d}".format(number)

print("Container IDs created!")

Container IDs created!

In [6]:
# ---------------------------------------------------------
# 5. OUTPUT FILE
# ---------------------------------------------------------

output_file = "AtmoSync_Streaming_Data.csv"

columns = [
    "Container_ID",
    "Timestamp",
    "Temperature_C",
    "Humidity_Percent",
    "Latitude",
    "Longitude"
]


# Create a fresh output file
with open(
    output_file,
    "w",
    newline="",
    encoding="utf-8"
) as file:

    writer = csv.DictWriter(
        file,
        fieldnames=columns
    )

    writer.writeheader()


print("Output file created:", output_file)

Output file created: AtmoSync_Streaming_Data.csv

In [7]:
# ---------------------------------------------------------
# 6. GENERATE EXACTLY 100 RECORDS
# ---------------------------------------------------------

print()
print("==============================================")
print("ATMOSYNC STREAMING STARTED")
print("==============================================")
print("Generating exactly 100 records...")
print("One record every 2 seconds")
print()


record_number = 0

try:

    while record_number < 100:

        # Select source row
        row = df.iloc[record_number % len(df)]

        # Increase record number
        record_number = record_number + 1

        # Container ID
        container_id = container_ids[
            row["location_name"]
        ]

        # Current timestamp
        timestamp = datetime.now().strftime(
            "%Y-%m-%d %H:%M:%S"
        )

        # Create AtmoSync record
        record = {
            "Container_ID": container_id,
            "Timestamp": timestamp,
            "Temperature_C": row["temperature_celsius"],
            "Humidity_Percent": row["humidity"],
            "Latitude": row["latitude"],
            "Longitude": row["longitude"]
        }

        # Save record to CSV
        with open(
            output_file,
            "a",
            newline="",
            encoding="utf-8"
        ) as file:

            writer = csv.DictWriter(
                file,
                fieldnames=columns
            )

            writer.writerow(record)

        # Display record
        print(
            "Record {:03d} | Container: {} | "
            "Temperature: {} C | Humidity: {}% | "
            "Location: {}".format(
                record_number,
                container_id,
                row["temperature_celsius"],
                row["humidity"],
                row["location_name"]
            )
        )

        # Wait before next record
        if record_number < 100:
            time.sleep(2)


except KeyboardInterrupt:

    print()
    print("Streaming manually stopped.")

==============================================
ATMOSYNC STREAMING STARTED
==============================================
Generating exactly 100 records...
One record every 2 seconds

Record 001 | Container: CONT_0001 | Temperature: 26.6 C | Humidity: 24% | Location: Kabul
Record 002 | Container: CONT_0002 | Temperature: 19.0 C | Humidity: 94% | Location: Tirana
Record 003 | Container: CONT_0003 | Temperature: 23.0 C | Humidity: 29% | Location: Algiers
Record 004 | Container: CONT_0004 | Temperature: 6.3 C | Humidity: 61% | Location: Andorra La Vella
Record 005 | Container: CONT_0005 | Temperature: 26.0 C | Humidity: 89% | Location: Luanda
Record 006 | Container: CONT_0006 | Temperature: 26.0 C | Humidity: 84% | Location: Saint John's
Record 007 | Container: CONT_0007 | Temperature: 8.0 C | Humidity: 93% | Location: Buenos Aires
Record 008 | Container: CONT_0008 | Temperature: 19.0 C | Humidity: 40% | Location: Yerevan
Record 009 | Container: CONT_0009 | Temperature: 9.0 C | Humidity: 87% | Location: Canberra
Record 010 | Container: CONT_0010 | Temperature: 16.0 C | Humidity: 63% | Location: Vienna
Record 011 | Container: CONT_0011 | Temperature: 17.0 C | Humidity: 68% | Location: Baku
Record 012 | Container: CONT_0012 | Temperature: 27.0 C | Humidity: 89% | Location: Nassau
Record 013 | Container: CONT_0013 | Temperature: 36.0 C | Humidity: 33% | Location: Manama
Record 014 | Container: CONT_0014 | Temperature: 38.4 C | Humidity: 31% | Location: Dhaka
Record 015 | Container: CONT_0015 | Temperature: 28.0 C | Humidity: 74% | Location: Bridgetown
Record 016 | Container: CONT_0016 | Temperature: 17.0 C | Humidity: 29% | Location: Minsk
Record 017 | Container: CONT_0017 | Temperature: 15.0 C | Humidity: 94% | Location: Brussels
Record 018 | Container: CONT_0018 | Temperature: 26.0 C | Humidity: 89% | Location: Belmopan
Record 019 | Container: CONT_0019 | Temperature: 28.0 C | Humidity: 79% | Location: Porto-Novo
Record 020 | Container: CONT_0020 | Temperature: 18.2 C | Humidity: 50% | Location: Thimphu
Record 021 | Container: CONT_0021 | Temperature: 12.3 C | Humidity: 77% | Location: Sucre
Record 022 | Container: CONT_0022 | Temperature: 19.0 C | Humidity: 64% | Location: Sarajevo
Record 023 | Container: CONT_0023 | Temperature: 22.0 C | Humidity: 43% | Location: Gaborone
Record 024 | Container: CONT_0024 | Temperature: 23.1 C | Humidity: 98% | Location: Bras
Record 025 | Container: CONT_0025 | Temperature: 32.0 C | Humidity: 84% | Location: Bandar Seri Begawan
Record 026 | Container: CONT_0026 | Temperature: 12.0 C | Humidity: 77% | Location: Sofia
Record 027 | Container: CONT_0027 | Temperature: 32.0 C | Humidity: 67% | Location: Ouagadougou
Record 028 | Container: CONT_0028 | Temperature: 21.1 C | Humidity: 66% | Location: Bujumbura
Record 029 | Container: CONT_0029 | Temperature: 27.4 C | Humidity: 44% | Location: Ivory
Record 030 | Container: CONT_0030 | Temperature: 22.0 C | Humidity: 69% | Location: Praia
Record 031 | Container: CONT_0031 | Temperature: 38.0 C | Humidity: 45% | Location: Phnom Penh
Record 032 | Container: CONT_0032 | Temperature: 25.0 C | Humidity: 78% | Location: Yaounde
Record 033 | Container: CONT_0033 | Temperature: 12.0 C | Humidity: 71% | Location: Ottawa
Record 034 | Container: CONT_0034 | Temperature: 28.4 C | Humidity: 60% | Location: Bangui
Record 035 | Container: CONT_0035 | Temperature: 37.2 C | Humidity: 27% | Location: N'djamena
Record 036 | Container: CONT_0036 | Temperature: 1.0 C | Humidity: 93% | Location: Santiago
Record 037 | Container: CONT_0037 | Temperature: 29.0 C | Humidity: 22% | Location: Beijing
Record 038 | Container: CONT_0038 | Temperature: 15.9 C | Humidity: 62% | Location: Bogot
Record 039 | Container: CONT_0039 | Temperature: 27.5 C | Humidity: 73% | Location: Moroni
Record 040 | Container: CONT_0040 | Temperature: 29.6 C | Humidity: 66% | Location: Brazzaville
Record 041 | Container: CONT_0041 | Temperature: 21.0 C | Humidity: 100% | Location: San Juan
Record 042 | Container: CONT_0042 | Temperature: 16.0 C | Humidity: 82% | Location: Zagreb
Record 043 | Container: CONT_0043 | Temperature: 26.0 C | Humidity: 84% | Location: Havana
Record 044 | Container: CONT_0044 | Temperature: 25.0 C | Humidity: 39% | Location: Nicosia
Record 045 | Container: CONT_0045 | Temperature: 18.0 C | Humidity: 49% | Location: Prague
Record 046 | Container: CONT_0046 | Temperature: 29.4 C | Humidity: 67% | Location: Kinshasa
Record 047 | Container: CONT_0047 | Temperature: 16.0 C | Humidity: 55% | Location: Copenhagen
Record 048 | Container: CONT_0048 | Temperature: 31.8 C | Humidity: 68% | Location: Djibouti
Record 049 | Container: CONT_0049 | Temperature: 27.2 C | Humidity: 78% | Location: Roseau
Record 050 | Container: CONT_0050 | Temperature: 23.0 C | Humidity: 94% | Location: Santo Domingo
Record 051 | Container: CONT_0051 | Temperature: 11.9 C | Humidity: 92% | Location: Quito
Record 052 | Container: CONT_0052 | Temperature: 27.0 C | Humidity: 32% | Location: Cairo
Record 053 | Container: CONT_0053 | Temperature: 26.0 C | Humidity: 94% | Location: San Salvador
Record 054 | Container: CONT_0054 | Temperature: 30.0 C | Humidity: 89% | Location: Malabo
Record 055 | Container: CONT_0055 | Temperature: 22.6 C | Humidity: 42% | Location: Asmara
Record 056 | Container: CONT_0056 | Temperature: 19.0 C | Humidity: 43% | Location: Tallinn
Record 057 | Container: CONT_0057 | Temperature: 22.2 C | Humidity: 39% | Location: Mbabane
Record 058 | Container: CONT_0058 | Temperature: 22.3 C | Humidity: 48% | Location: Addis Ababa
Record 059 | Container: CONT_0059 | Temperature: 26.0 C | Humidity: 89% | Location: Suva
Record 060 | Container: CONT_0060 | Temperature: 22.0 C | Humidity: 33% | Location: Helsinki
Record 061 | Container: CONT_0061 | Temperature: 15.0 C | Humidity: 72% | Location: Paris
Record 062 | Container: CONT_0062 | Temperature: 29.0 C | Humidity: 75% | Location: Libreville
Record 063 | Container: CONT_0063 | Temperature: 23.0 C | Humidity: 83% | Location: Banjul
Record 064 | Container: CONT_0064 | Temperature: 16.0 C | Humidity: 68% | Location: Tbilisi
Record 065 | Container: CONT_0065 | Temperature: 22.0 C | Humidity: 38% | Location: Berlin
Record 066 | Container: CONT_0066 | Temperature: 29.0 C | Humidity: 84% | Location: Accra
Record 067 | Container: CONT_0067 | Temperature: 23.0 C | Humidity: 38% | Location: Athens
Record 068 | Container: CONT_0068 | Temperature: 28.0 C | Humidity: 79% | Location: Saint George's
Record 069 | Container: CONT_0069 | Temperature: 20.0 C | Humidity: 88% | Location: Guatemala City
Record 070 | Container: CONT_0070 | Temperature: 26.0 C | Humidity: 94% | Location: Conakry
Record 071 | Container: CONT_0071 | Temperature: 24.0 C | Humidity: 89% | Location: Bissau
Record 072 | Container: CONT_0072 | Temperature: 24.0 C | Humidity: 100% | Location: Georgetown
Record 073 | Container: CONT_0073 | Temperature: 21.0 C | Humidity: 88% | Location: Port-Au-Prince
Record 074 | Container: CONT_0074 | Temperature: 24.0 C | Humidity: 57% | Location: Vatican City
Record 075 | Container: CONT_0075 | Temperature: 23.0 C | Humidity: 78% | Location: Tegucigalpa
Record 076 | Container: CONT_0076 | Temperature: 20.0 C | Humidity: 43% | Location: Budapest
Record 077 | Container: CONT_0077 | Temperature: 7.0 C | Humidity: 93% | Location: Grindavik
Record 078 | Container: CONT_0078 | Temperature: 42.0 C | Humidity: 13% | Location: New Delhi
Record 079 | Container: CONT_0079 | Temperature: 32.0 C | Humidity: 63% | Location: Jakarta
Record 080 | Container: CONT_0080 | Temperature: 24.0 C | Humidity: 25% | Location: Tehran
Record 081 | Container: CONT_0081 | Temperature: 33.0 C | Humidity: 17% | Location: Baghdad
Record 082 | Container: CONT_0082 | Temperature: 14.0 C | Humidity: 94% | Location: Dublin
Record 083 | Container: CONT_0083 | Temperature: 25.0 C | Humidity: 54% | Location: Jerusalem
Record 084 | Container: CONT_0084 | Temperature: 24.0 C | Humidity: 57% | Location: Rome
Record 085 | Container: CONT_0085 | Temperature: 21.9 C | Humidity: 84% | Location: Norman Gardens
Record 086 | Container: CONT_0086 | Temperature: 24.0 C | Humidity: 47% | Location: Tokyo
Record 087 | Container: CONT_0087 | Temperature: 23.0 C | Humidity: 29% | Location: Amman
Record 088 | Container: CONT_0088 | Temperature: 16.0 C | Humidity: 34% | Location: Astana
Record 089 | Container: CONT_0089 | Temperature: 23.0 C | Humidity: 61% | Location: Nairobi
Record 090 | Container: CONT_0090 | Temperature: 28.8 C | Humidity: 75% | Location: Tarawa
Record 091 | Container: CONT_0091 | Temperature: 30.4 C | Humidity: 44% | Location: Kuwait City
Record 092 | Container: CONT_0092 | Temperature: 22.5 C | Humidity: 59% | Location: Bishkek
Record 093 | Container: CONT_0093 | Temperature: 28.0 C | Humidity: 74% | Location: Laos
Record 094 | Container: CONT_0094 | Temperature: 17.0 C | Humidity: 48% | Location: Riga
Record 095 | Container: CONT_0095 | Temperature: 22.0 C | Humidity: 65% | Location: Beirut
Record 096 | Container: CONT_0096 | Temperature: 18.0 C | Humidity: 52% | Location: Maseru
Record 097 | Container: CONT_0097 | Temperature: 26.0 C | Humidity: 94% | Location: Monrovia
Record 098 | Container: CONT_0098 | Temperature: 33.0 C | Humidity: 63% | Location: Nan
Record 099 | Container: CONT_0099 | Temperature: 15.0 C | Humidity: 72% | Location: Vaduz
Record 100 | Container: CONT_0100 | Temperature: 17.0 C | Humidity: 39% | Location: Vilnius

In [8]:
# ---------------------------------------------------------
# 7. FINAL MESSAGE
# ---------------------------------------------------------

print()
print("==============================================")
print("ATMOSYNC STREAMING COMPLETED")
print("==============================================")
print("Total records generated:", record_number)
print("Data saved in:", output_file)

==============================================
ATMOSYNC STREAMING COMPLETED
==============================================
Total records generated: 100
Data saved in: AtmoSync_Streaming_Data.csv

In [9]:
# ---------------------------------------------------------
# 8. VERIFY GENERATED DATA
# ---------------------------------------------------------

streaming_df = pd.read_csv("AtmoSync_Streaming_Data.csv")

print("AtmoSync streaming file loaded!")
print("Total records:", len(streaming_df))

print()
print("First 5 records:")
display(streaming_df.head())

print()
print("Last 5 records:")
display(streaming_df.tail())

print()
print("Columns:")
print(streaming_df.columns.tolist())

AtmoSync streaming file loaded!
Total records: 100

First 5 records:

,Container_ID,Timestamp,Temperature_C,Humidity_Percent,Latitude,Longitude
0,CONT_0001,2026-09-15 20:03:45,26.6,24,34.52,69.18
1,CONT_0002,2026-09-15 20:03:47,19.0,94,41.33,19.82
2,CONT_0003,2026-09-15 20:03:49,23.0,29,36.76,3.05
3,CONT_0004,2026-09-15 20:03:51,6.3,61,42.50,1.52
4,CONT_0005,2026-09-15 20:03:53,26.0,89,-8.84,13.23

Last 5 records:

,Container_ID,Timestamp,Temperature_C,Humidity_Percent,Latitude,Longitude
95,CONT_0096,2026-09-15 20:06:56,18.0,52,-29.32,27.48
96,CONT_0097,2026-09-15 20:06:58,26.0,94,6.31,-10.80
97,CONT_0098,2026-09-15 20:07:00,33.0,63,18.78,100.78
98,CONT_0099,2026-09-15 20:07:02,15.0,72,47.13,9.52
99,CONT_0100,2026-09-15 20:07:04,17.0,39,54.68,25.32

Columns:
['Container_ID', 'Timestamp', 'Temperature_C', 'Humidity_Percent', 'Latitude', 'Longitude']

In [10]:
# ---------------------------------------------------------
# 9. CHECK DATA QUALITY
# ---------------------------------------------------------

print("Missing values:")
print(streaming_df.isnull().sum())

print()
print("Duplicate records:")
print(streaming_df.duplicated().sum())

Missing values:
Container_ID        0
Timestamp           0
Temperature_C       0
Humidity_Percent    0
Latitude            0
Longitude           0
dtype: int64

Duplicate records:
0